server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/pokedex
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      host: 172.18.0.3
      port: 27017
      database: pokedex

appDescription: "Pokedex API"
appVersion: "1.0.0"